/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.CandidateProfile;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import static javax.management.Query.match;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CandidateProfile candidateProfile;
    
    public CreateJPanel(CandidateProfile candidateProfile) {
        initComponents();
        this.candidateProfile=candidateProfile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDOb = new javax.swing.JLabel();
        lblTelephnNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedRecordNum = new javax.swing.JLabel();
        lblHealthPlanBeneNum = new javax.swing.JLabel();
        lblBankACNum = new javax.swing.JLabel();
        lblCertLicenNum = new javax.swing.JLabel();
        lblVehIdentifier = new javax.swing.JLabel();
        lblDevIdentifier = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIpAdress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtTelephnNum = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedRecordNum = new javax.swing.JTextField();
        txtHealthPlanBeneNum = new javax.swing.JTextField();
        txtBankACNum = new javax.swing.JTextField();
        txtCertLicenNum = new javax.swing.JTextField();
        txtVehIdentifier = new javax.swing.JTextField();
        txtDevIdentifier = new javax.swing.JTextField();
        txtLinkdIn = new javax.swing.JTextField();
        txtIpAdress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblProfilePicture = new javax.swing.JLabel();
        btnProfilePicture = new javax.swing.JButton();
        txtDOb = new com.toedter.calendar.JDateChooser();
        lblErrorMessage = new javax.swing.JLabel();
        lblErrMsg2 = new javax.swing.JLabel();
        lblGeoErrMsg = new javax.swing.JLabel();
        lblErrorIpAdress = new javax.swing.JLabel();
        lblErrorLinkedIn = new javax.swing.JLabel();
        lblErrorFax = new javax.swing.JLabel();
        lblErrorEmailId = new javax.swing.JLabel();
        lblErrorSsn = new javax.swing.JLabel();
        lblErrorMedRecNum = new javax.swing.JLabel();
        lblErrorHealthPlanBeneNum = new javax.swing.JLabel();
        lblErrorBankAcNum = new javax.swing.JLabel();
        lblErrorCertLicenceNum = new javax.swing.JLabel();
        lblErrorVehIdentifierNum = new javax.swing.JLabel();
        lblErrorDevIdentifierNum = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("New Candidate Details");

        lblName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name :");

        lblGeoData.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblGeoData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGeoData.setText("Geography :");

        lblDOb.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblDOb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDOb.setText("Date of Birth :");

        lblTelephnNum.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblTelephnNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelephnNum.setText("Telephone No. :");

        lblFaxNum.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblFaxNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFaxNum.setText("FAX No. :");

        lblEmailID.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblEmailID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmailID.setText("Email ID :");

        lblSsn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSsn.setText("SSN :");

        lblMedRecordNum.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMedRecordNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedRecordNum.setText("Medical Record No. :");

        lblHealthPlanBeneNum.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblHealthPlanBeneNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHealthPlanBeneNum.setText("Health Plan Beneficiary No. :");

        lblBankACNum.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblBankACNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankACNum.setText("Bank A/C No. :");

        lblCertLicenNum.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblCertLicenNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCertLicenNum.setText("Certificate/License No. :");

        lblVehIdentifier.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblVehIdentifier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehIdentifier.setText("Vehicle Identifier No. :");

        lblDevIdentifier.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblDevIdentifier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDevIdentifier.setText("Device Identifier No. :");

        lblLinkedIn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedIn.setText("LinkedIn ID :");

        lblIpAdress.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblIpAdress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIpAdress.setText("IP Address :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        txtGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoDataActionPerformed(evt);
            }
        });

        txtTelephnNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelephnNumKeyPressed(evt);
            }
        });

        txtFaxNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFaxNumKeyPressed(evt);
            }
        });

        txtEmailID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailIDKeyPressed(evt);
            }
        });

        txtSsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSsnKeyPressed(evt);
            }
        });

        txtMedRecordNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMedRecordNumKeyPressed(evt);
            }
        });

        txtHealthPlanBeneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHealthPlanBeneNumKeyPressed(evt);
            }
        });

        txtBankACNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBankACNumKeyPressed(evt);
            }
        });

        txtCertLicenNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertLicenNumActionPerformed(evt);
            }
        });
        txtCertLicenNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCertLicenNumKeyPressed(evt);
            }
        });

        txtVehIdentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVehIdentifierKeyPressed(evt);
            }
        });

        txtDevIdentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDevIdentifierKeyPressed(evt);
            }
        });

        txtLinkdIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLinkdInKeyPressed(evt);
            }
        });

        txtIpAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpAdressActionPerformed(evt);
            }
        });
        txtIpAdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIpAdressKeyPressed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnProfilePicture.setText("Upload Profile Picture");
        btnProfilePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilePictureActionPerformed(evt);
            }
        });

        lblGeoErrMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblGeoErrMsgKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4))
                                .addComponent(btnProfilePicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDOb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTelephnNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFaxNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEmailID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMedRecordNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblBankACNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCertLicenNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVehIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDevIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblIpAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHealthPlanBeneNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIpAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorIpAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDevIdentifier, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehIdentifier, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCertLicenNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBankACNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHealthPlanBeneNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedRecordNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSsn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFaxNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelephnNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDOb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtGeoData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtLinkdIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(lblErrMsg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGeoErrMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorMedRecNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorHealthPlanBeneNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorBankAcNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorCertLicenceNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorVehIdentifierNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorDevIdentifierNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGeoData))
                                    .addComponent(lblGeoErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDOb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDOb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTelephnNum)
                                        .addComponent(txtTelephnNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFaxNum))
                                    .addComponent(lblErrorFax))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmailID)
                                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrorEmailId)))
                            .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSsn)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProfilePicture)
                            .addComponent(lblErrorSsn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedRecordNum)
                            .addComponent(txtMedRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorMedRecNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHealthPlanBeneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorHealthPlanBeneNum)
                            .addComponent(lblHealthPlanBeneNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankACNum)
                            .addComponent(txtBankACNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorBankAcNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCertLicenNum)
                            .addComponent(txtCertLicenNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorCertLicenceNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehIdentifier)
                            .addComponent(txtVehIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorVehIdentifierNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDevIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorDevIdentifierNum)
                            .addComponent(lblDevIdentifier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinkdIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorLinkedIn)
                            .addComponent(lblLinkedIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorIpAdress)
                            .addComponent(lblIpAdress))))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoDataActionPerformed

    private void txtCertLicenNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertLicenNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertLicenNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(txtName.getText().isEmpty() || txtGeoData.getText().isEmpty() || txtTelephnNum.getText().isEmpty() || txtFaxNum.getText().isEmpty() || txtEmailID.getText().isEmpty() || txtSsn.getText().isEmpty() || txtMedRecordNum.getText().isEmpty() || txtHealthPlanBeneNum.getText().isEmpty() || txtBankACNum.getText().isEmpty() || txtCertLicenNum.getText().isEmpty() || txtVehIdentifier.getText().isEmpty() || txtDevIdentifier.getText().isEmpty() || txtLinkdIn.getText().isEmpty() || txtIpAdress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter the Mandatory fields");
    }else {
        
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault());   //Define the format of Date
        String Date_selector = sf.format(txtDOb.getDate());
        
        candidateProfile.setName(txtName.getText());
        candidateProfile.setGeoData(txtGeoData.getText());
        //candidateProfile.setdOb(Date_selector);
        candidateProfile.setEmailID(txtEmailID.getText());
        candidateProfile.setVehIdentifier(txtVehIdentifier.getText());
        candidateProfile.setDevIdentifier(txtDevIdentifier.getText());
        candidateProfile.setLinkedIn(txtLinkdIn.getText());
        candidateProfile.setIpAdress(txtIpAdress.getText());
       
       try{
           candidateProfile.setdOb(Date_selector);
           candidateProfile.setTelephnNum(Long.parseLong(txtTelephnNum.getText()));
           candidateProfile.setFaxNum(Long.parseLong(txtFaxNum.getText()));
           candidateProfile.setSsn(Long.parseLong(txtSsn.getText()));
           candidateProfile.setMedRecordNum(Long.parseLong(txtMedRecordNum.getText()));
           candidateProfile.setHealthPlanBeneNum(Long.parseLong(txtHealthPlanBeneNum.getText()));
           candidateProfile.setBankACNum(Long.parseLong(txtBankACNum.getText()));
           candidateProfile.setCertLicenNum(Long.parseLong(txtCertLicenNum.getText()));
       }catch(NumberFormatException e){// handle your exception
           e.printStackTrace();
       }
       
       JOptionPane.showMessageDialog(this, "Candidate Information Saved");
        }     
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void txtIpAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpAdressActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txtIpAdressActionPerformed

    private void btnProfilePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilePictureActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
    filechooser.setDialogTitle("Choose Your File");
    filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int returnval = filechooser.showOpenDialog(this);
    if (returnval == JFileChooser.APPROVE_OPTION)
    {
        File file = filechooser.getSelectedFile();
        BufferedImage bi;
        BufferedImage img = null;
        try {
            // display the image in a Jlabel
            bi = ImageIO.read(file);
            Image dimg = bi.getScaledInstance(lblProfilePicture.getWidth(),lblProfilePicture.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);
            lblProfilePicture.setIcon(icon);
            candidateProfile.setImage(icon);
        } catch(IOException e) {
           e.printStackTrace(); // todo: implement proper error handeling
        }
    }
    }//GEN-LAST:event_btnProfilePictureActionPerformed

    private void txtTelephnNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephnNumKeyPressed
                                       
        // TODO add your handling code here:
        
        String phoneNumber = txtTelephnNum.getText();
        int length = phoneNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<10){
                txtTelephnNum.setEditable(true);
                lblErrorMessage.setText("Telephone number should be equal to 10 digits");
            }else{
                txtTelephnNum.setEditable(false);
                lblErrorMessage.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtTelephnNum.setEditable(true);
               
            }else{
                txtTelephnNum.setEditable(false);
                
            }
        
        }
    }//GEN-LAST:event_txtTelephnNumKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:

           char c = evt.getKeyChar();
           
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
                lblErrMsg2.setText(" ");
               txtName.setEditable(true);
               
           }else {
               if(!Character.isLetter(c)){
              // txtName.setEditable(false);
                lblErrMsg2.setText("Put a valid Name");
               }
           }
    }//GEN-LAST:event_txtNameKeyPressed

    private void lblGeoErrMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblGeoErrMsgKeyPressed
        // TODO add your handling code here:
        
//        String PATTERN="^[a-zA-Z]";
//        Pattern patt=Pattern.compile(PATTERN);
//        Matcher match= patt.matcher(txtName.getText());
//        if(!match.matches()){
//            lblGeoErrMsg.setText("Put a valid Address");
//        }else{
//            candidateProfile.setName(null);
//        }

           
    }//GEN-LAST:event_lblGeoErrMsgKeyPressed

    private void txtIpAdressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIpAdressKeyPressed

        String ipadd = txtIpAdress.getText();
        
        String digitRegEx = "(\\d{1,2}|(0|1)\\d{2}|2[0-4]\\d|25[0-5])";
        String ipRegEx = digitRegEx + "\\." + digitRegEx + "\\." + digitRegEx + "\\." + digitRegEx;
        
        Pattern pattern = Pattern.compile(ipRegEx);
        
        //pattern.matcher(ipadd).matches();
        if(!pattern.matcher(ipadd).matches())
        {
            lblErrorIpAdress.setText("Put a valid valid IP adress");
        }else{
            lblErrorIpAdress.setText(" ");
        }
   
        
    }//GEN-LAST:event_txtIpAdressKeyPressed

    private void txtLinkdInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkdInKeyPressed
        // TODO add your handling code here:
      
        String linkedIn = txtLinkdIn.getText();
        String PATTERN = "^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(linkedIn);
        if(!match.matches()){
            lblErrorLinkedIn.setText("Enter a valid LinkedIn Id!!");
        }else{
            lblErrorLinkedIn.setText(" ");
        }
       
    }//GEN-LAST:event_txtLinkdInKeyPressed

    private void txtEmailIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailIDKeyPressed
        // TODO add your handling code here:
        String emreg = "^[a-zA-Z0-9]+@[a-zA-Z]+\\.[a-zA-Z]+";
        Pattern ep = Pattern.compile(emreg);
        Matcher matcher = ep.matcher(txtEmailID.getText());
        if(!matcher.matches())
        {
        lblErrorEmailId.setText("Put valid emailID");
        }
        else
        {
            lblErrorEmailId.setText(null);
        }
    }//GEN-LAST:event_txtEmailIDKeyPressed

    private void txtFaxNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumKeyPressed
        // TODO add your handling code here:
        String faxNumber = txtFaxNum.getText();
        int length = faxNumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<10)
            {
                txtFaxNum.setEditable(true);
                lblErrorFax.setText("Input should be 10 digits");
            }
            else
            {
                txtFaxNum.setEditable(false);
                String Null = null;
                lblErrorFax.setText(Null);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtFaxNum.setEditable(true);
            }
            else
            {
                txtFaxNum.setEditable(false);
            }
    }//GEN-LAST:event_txtFaxNumKeyPressed
}
  
    private void txtSsnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSsnKeyPressed
        // TODO add your handling code here:
        String ssn = txtSsn.getText();
        int length = ssn.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<9){
                txtSsn.setEditable(true);
                lblErrorSsn.setText("SSN number should be equal to 9 digits");
            }else{
                txtSsn.setEditable(false);
                lblErrorSsn.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtSsn.setEditable(true);
               
            }else{
                txtSsn.setEditable(false);
                
            }
        
        }
        
        
 
    }//GEN-LAST:event_txtSsnKeyPressed

    private void txtVehIdentifierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehIdentifierKeyPressed
        // TODO add your handling code here:
 
       String vehIdentifier = txtVehIdentifier.getText();
        String PATTERN = "^[a-zA-Z0-9]+";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(vehIdentifier);
        if(!match.matches()){
            lblErrorVehIdentifierNum.setText("Enter a valid vehicle identifier!!");
        }else{
            lblErrorVehIdentifierNum.setText(" ");
        }
    }//GEN-LAST:event_txtVehIdentifierKeyPressed

    private void txtDevIdentifierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDevIdentifierKeyPressed
        // TODO add your handling code here:
        
        String devIdentifier = txtDevIdentifier.getText();
        int length = devIdentifier.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<15){
                txtDevIdentifier.setEditable(true);
                lblErrorDevIdentifierNum.setText("Telephone number should be equal to 15 digits");
            }else{
                txtDevIdentifier.setEditable(false);
                lblErrorDevIdentifierNum.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtDevIdentifier.setEditable(true);
               
            }else{
                txtDevIdentifier.setEditable(false);
                
            }
        
        }
        
        

    }//GEN-LAST:event_txtDevIdentifierKeyPressed

    private void txtCertLicenNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCertLicenNumKeyPressed
        // TODO add your handling code here:
        
        String CertLicense = txtCertLicenNum.getText();
        int length = CertLicense.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<8){
                txtCertLicenNum.setEditable(true);
                lblErrorCertLicenceNum.setText("Telephone number should be equal to 8 digits");
            }else{
                txtCertLicenNum.setEditable(false);
                lblErrorCertLicenceNum.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtCertLicenNum.setEditable(true);
               
            }else{
                txtCertLicenNum.setEditable(false);
                
            }
        
        }
        
        
        
    }//GEN-LAST:event_txtCertLicenNumKeyPressed

    private void txtBankACNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankACNumKeyPressed
        // TODO add your handling code here:
        String bankAcc = txtBankACNum.getText();
        int length = bankAcc.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<12){
                txtBankACNum.setEditable(true);
                lblErrorBankAcNum.setText("Bank A/c should be equal to 12 digits");
            }else{
                txtBankACNum.setEditable(false);
                lblErrorBankAcNum.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtBankACNum.setEditable(true);
               
            }else{
                txtBankACNum.setEditable(false);
                
            }
        
        }
        
  
    }//GEN-LAST:event_txtBankACNumKeyPressed

    private void txtHealthPlanBeneNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneNumKeyPressed
        // TODO add your handling code here:
        
       String healthPlanBeneNum = txtHealthPlanBeneNum.getText();
        int length = healthPlanBeneNum.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>'0' && evt.getKeyChar()<'9'){
            if(length<7){
                txtHealthPlanBeneNum.setEditable(true);
                 lblErrorHealthPlanBeneNum.setText("Health Beneficiary Number should be 7 digits");
            }else{
                txtHealthPlanBeneNum.setEditable(false);
                lblErrorHealthPlanBeneNum.setText(" ");
            }
        }else {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtHealthPlanBeneNum.setEditable(true);
            }else{
                txtHealthPlanBeneNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtHealthPlanBeneNumKeyPressed

    private void txtMedRecordNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedRecordNumKeyPressed
        // TODO add your handling code here:
        
        String medRecNo = txtMedRecordNum.getText();
        int length = medRecNo.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>'0' && evt.getKeyChar()<'9'){
            if(length<7){
                txtMedRecordNum.setEditable(true);
                 lblErrorMedRecNum.setText("Health Beneficiary Number should be 7 digits");
            }else{
                txtMedRecordNum.setEditable(false);
                lblErrorMedRecNum.setText(" ");
            }
        }else {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtMedRecordNum.setEditable(true);
            }else{
                txtMedRecordNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtMedRecordNumKeyPressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProfilePicture;
    private javax.swing.JButton btnSave;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBankACNum;
    private javax.swing.JLabel lblCertLicenNum;
    private javax.swing.JLabel lblDOb;
    private javax.swing.JLabel lblDevIdentifier;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblErrMsg2;
    private javax.swing.JLabel lblErrorBankAcNum;
    private javax.swing.JLabel lblErrorCertLicenceNum;
    private javax.swing.JLabel lblErrorDevIdentifierNum;
    private javax.swing.JLabel lblErrorEmailId;
    private javax.swing.JLabel lblErrorFax;
    private javax.swing.JLabel lblErrorHealthPlanBeneNum;
    private javax.swing.JLabel lblErrorIpAdress;
    private javax.swing.JLabel lblErrorLinkedIn;
    private javax.swing.JLabel lblErrorMedRecNum;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblErrorSsn;
    private javax.swing.JLabel lblErrorVehIdentifierNum;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblGeoErrMsg;
    private javax.swing.JLabel lblHealthPlanBeneNum;
    private javax.swing.JLabel lblIpAdress;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedRecordNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTelephnNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehIdentifier;
    private javax.swing.JTextField txtBankACNum;
    private javax.swing.JTextField txtCertLicenNum;
    private com.toedter.calendar.JDateChooser txtDOb;
    private javax.swing.JTextField txtDevIdentifier;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlanBeneNum;
    private javax.swing.JTextField txtIpAdress;
    private javax.swing.JTextField txtLinkdIn;
    private javax.swing.JTextField txtMedRecordNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTelephnNum;
    private javax.swing.JTextField txtVehIdentifier;
    // End of variables declaration//GEN-END:variables
}
