/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Person;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.VitalSigns;

/**
 *
 * @author adity
 */
public class UpdateVitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateVitalSignsJPanel
     */
    
    private VitalSigns vitalSign;
    private JPanel workAreaJPanel;
    private Boolean isEdit = Boolean.FALSE;
    
    
    public UpdateVitalSignsJPanel(JPanel jpanel, VitalSigns vitalSign, Boolean isEdit) {
        initComponents();
        this.workAreaJPanel = jpanel;
        this.vitalSign = vitalSign;
        this.isEdit = isEdit;
        
        populateVitalSignDetails();
        modifyTextFields(this.isEdit);
        
        if(isEdit){
            btnUpdateVitals.setEnabled(true);
        }else
            btnUpdateVitals.setEnabled(false);
    }
    
    
    private void populateVitalSignDetails() {
        txtRespiratoryRatee.setText(String.valueOf(vitalSign.getRespiratoryRate()));
        txtHeartRatee.setText(String.valueOf(vitalSign.getHeartRate()));
        txtBloodPressuree.setText(String.valueOf(vitalSign.getBloodPressure()));
        txtWeightinPounds.setText(String.valueOf(vitalSign.getWeight()));
    }
        
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeartRate = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtRespiratoryRatee = new javax.swing.JTextField();
        txtHeartRatee = new javax.swing.JTextField();
        txtBloodPressuree = new javax.swing.JTextField();
        txtWeightinPounds = new javax.swing.JTextField();
        btnUpdateVitals = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblRespiratoryRate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        lblHeartRate.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lblHeartRate.setForeground(new java.awt.Color(153, 255, 255));
        lblHeartRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHeartRate.setText("Heart Rate :");

        lblBloodPressure.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lblBloodPressure.setForeground(new java.awt.Color(153, 255, 255));
        lblBloodPressure.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBloodPressure.setText("Systolic Blood Pressure:");

        lblWeight.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(153, 255, 255));
        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWeight.setText("Weight in Pounds :");

        txtRespiratoryRatee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespiratoryRateeActionPerformed(evt);
            }
        });

        txtHeartRatee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateeActionPerformed(evt);
            }
        });

        txtBloodPressuree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureeActionPerformed(evt);
            }
        });

        txtWeightinPounds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightinPoundsActionPerformed(evt);
            }
        });

        btnUpdateVitals.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateVitals.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnUpdateVitals.setText("Update");
        btnUpdateVitals.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        btnUpdateVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVitalsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Patient Vitals Sign");

        lblRespiratoryRate.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lblRespiratoryRate.setForeground(new java.awt.Color(153, 255, 255));
        lblRespiratoryRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRespiratoryRate.setText("Respiratory Rate :");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHeartRatee, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWeightinPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBloodPressuree, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdateVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(txtRespiratoryRatee, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lblRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeartRatee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBloodPressuree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeightinPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(txtRespiratoryRatee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespiratoryRateeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespiratoryRateeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateeActionPerformed

    private void txtHeartRateeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateeActionPerformed

    private void txtBloodPressureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureeActionPerformed

    private void txtWeightinPoundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightinPoundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightinPoundsActionPerformed

    private void btnUpdateVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVitalsActionPerformed
        // TODO add your handling code here:
        try {
            int respiratoryRate = Integer.parseInt(txtRespiratoryRatee.getText());
            int heartRate = Integer.parseInt(txtHeartRatee.getText());
            int bloodPressure = Integer.parseInt(txtBloodPressuree.getText());
            int weight = Integer.parseInt(txtWeightinPounds.getText());
            vitalSign.setRespiratoryRate(respiratoryRate);
            vitalSign.setHeartRate(heartRate);
            vitalSign.setBloodPressure(bloodPressure);
            vitalSign.setWeight(weight);
            /*Set current date and time as TimeStamp*/
            vitalSign.setTimestamp(new Date());
            JOptionPane.showMessageDialog(this, "Vital signs updated!!", "Update", 
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please enter correct values", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        modifyTextFields(false);

    }//GEN-LAST:event_btnUpdateVitalsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void modifyTextFields(Boolean isEdit) {
       
        if (isEdit) {
            txtRespiratoryRatee.setEnabled(true);
            txtHeartRatee.setEnabled(true);
            txtBloodPressuree.setEnabled(true);
            txtWeightinPounds.setEnabled(true);
        } else {
            txtRespiratoryRatee.setEnabled(false);
            txtHeartRatee.setEnabled(false);
            txtBloodPressuree.setEnabled(false);
            txtWeightinPounds.setEnabled(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateVitals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBloodPressuree;
    private javax.swing.JTextField txtHeartRatee;
    private javax.swing.JTextField txtRespiratoryRatee;
    private javax.swing.JTextField txtWeightinPounds;
    // End of variables declaration//GEN-END:variables
}
