/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Person;

import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author adity
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    
    private PersonDirectory personDirectory;
    private JPanel workAreaJPanel;
    
    public CreatePersonJPanel(JPanel workAreaJPanel,PersonDirectory personDirectory) {
        initComponents();
        this.workAreaJPanel = workAreaJPanel;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPersonName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnback1 = new javax.swing.JButton();
        btnAddPerson = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        jRadioBtnMale = new javax.swing.JRadioButton();
        jRadioBtnFemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtZipCode1 = new javax.swing.JTextField();
        lblNameError = new javax.swing.JLabel();
        lblPersonAgeError = new javax.swing.JLabel();
        lblZipcodeError = new javax.swing.JLabel();
        lblCityError = new javax.swing.JLabel();
        lblCommunityError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Person Details");

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name of Person :");

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Age :");

        txtPersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonNameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        btnback1.setBackground(new java.awt.Color(0, 0, 0));
        btnback1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(153, 255, 255));
        btnback1.setText("<< Back");
        btnback1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btnAddPerson.setBackground(new java.awt.Color(0, 0, 0));
        btnAddPerson.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnAddPerson.setForeground(new java.awt.Color(153, 255, 255));
        btnAddPerson.setText("Add Person");
        btnAddPerson.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("City :");

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Community :");

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("House :");

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Gender :");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        jRadioBtnMale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup.add(jRadioBtnMale);
        jRadioBtnMale.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jRadioBtnMale.setForeground(new java.awt.Color(153, 255, 255));
        jRadioBtnMale.setText("Male");
        jRadioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnMaleActionPerformed(evt);
            }
        });

        jRadioBtnFemale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup.add(jRadioBtnFemale);
        jRadioBtnFemale.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jRadioBtnFemale.setForeground(new java.awt.Color(153, 255, 255));
        jRadioBtnFemale.setText("Female");
        jRadioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnFemaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Zip Code :");

        txtZipCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCode1ActionPerformed(evt);
            }
        });

        lblNameError.setForeground(new java.awt.Color(255, 255, 255));

        lblPersonAgeError.setForeground(new java.awt.Color(255, 255, 255));

        lblZipcodeError.setForeground(new java.awt.Color(255, 255, 255));

        lblCityError.setForeground(new java.awt.Color(255, 255, 255));

        lblCommunityError.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioBtnMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioBtnFemale))
                                    .addComponent(btnAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(txtCommunity)
                                            .addComponent(txtPersonName)
                                            .addComponent(txtAge)
                                            .addComponent(txtHouse)
                                            .addComponent(txtZipCode1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                            .addComponent(lblPersonAgeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblZipcodeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCommunityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioBtnMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioBtnFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersonAgeError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCommunityError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCityError, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipcodeError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
        //populatePersonsTable(personDirectory.getPersonHistory());
        
        
        
    }//GEN-LAST:event_btnback1ActionPerformed

//    private void populatePersonsTable(ArrayList<Person> personsList) {
//        DefaultTableModel model = (DefaultTableModel) tblManagePersonDetails.getModel();
//        model.setRowCount(0);
//        if(personsList.isEmpty())
//        {
//            JOptionPane.showMessageDialog(this, "No Person's found. Please add"
//                    + " Person's", "Warning", JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
//        for (Person person : personsList) {
//            Object[] row = new Object[7];
//            row[0] = person;
//            row[1] = person.getAge();
//            row[2] = person.getGender();
//            row[3] = person.getHouse();
//            row[4] = person.getCommunity();
//            row[5] = person.getCity();
//            row[6] = person.getZipcode();
//         
//            
////            if(person.getPatient()!=null)
////            {
////                row[2] = person.getPatient().getPatientID();
////            }
////            else
////            {
////                row[2] = "Patient Not Created";
////            }
//            model.addRow(row);
//        }
//    
//    }
    
    private void clearFields()
    {
        txtPersonName.setText("");
        txtAge.setText("");
        txtHouse.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        txtZipCode1.setText("");
        buttonGroup.clearSelection();    
    }
    
    
    private Boolean checkBlankInput()
    {
        if(txtPersonName.getText().isEmpty()||txtAge.getText().isEmpty()||txtHouse.getText().isEmpty()||txtCommunity.getText().isEmpty()||txtCity.getText().isEmpty()||txtZipCode1.getText().isEmpty())
        {
            return false;
        }
        else{
            return true;
        }
    }
    
    
    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
//        if (checkBlankInput()==Boolean.TRUE)
//        {
//            String personName= txtPersonName.getText();
//            int age= Integer.parseInt(txtAge.getText());
//            String houseAddress = txtHouse.getText();
//            String community = txtCommunity.getText();
//            String city = txtCity.getText();
//            int zipcode = Integer.parseInt(txtZipCode1.getText());
//            
//            String charPattern = "^[a-zA-z]+";
//            Pattern expPersonName = Pattern.compile(charPattern);
//            
//            String agePattern = "^[0-9]{2}+";
//            Pattern expAge = Pattern.compile(agePattern);
//            
//            String zipcodePattern = "^[0-9]{5}+";
//            Pattern expZipCode = Pattern.compile(zipcodePattern);
//            
//            Matcher matcherPersonName = expPersonName.matcher(txtPersonName.getText());
//            if(!matcherPersonName.matches()){
//                lblNameError.setText("Enter a valid person name!!");
//            }else{
//                lblNameError.setText(" ");
//                Matcher matchNumber = expAge.matcher(txtAge.getText());
//                if(!matchNumber.matches()){
//                    lblPersonAgeError.setText("Enter a valid Age!!");
//                }else{
//                    lblPersonAgeError.setText(" ");
//                    Matcher matchZipCode = expZipCode.matcher(txtZipCode1.getText());
//                    if(!matchZipCode.matches()){
//                        lblZipcodeError.setText("Enter a valid Zipcode!!");
//                    }else{
//                        lblZipcodeError.setText(" ");
//                        Matcher matchCity = expPersonName.matcher(txtCity.getText());
//                        if(!matchCity.matches()){
//                            lblCityError.setText("Enter a valid City!!");
//                        }else{
//                            lblCityError.setText(" ");
//                            Matcher macthCommunity = expPersonName.matcher(txtCommunity.getText());
//                            if(!macthCommunity.matches()){
//                                lblCommunityError.setText("Enter a valid Community!!");
//                            }else{
//                                lblCommunityError.setText(" ");
//                                Person person=personDirectory.addPerson();
//                                person.setPersonName(personName);
//                                person.setAge(age);
//                                person.setHouse(houseAddress);
//                                person.setCommunity(community);
//                                person.setCity(city);
//                                person.setZipcode(zipcode);
//                                
//                                if(jRadioBtnFemale.isSelected()){
//                                    person.setGender(jRadioBtnFemale.getText());
//                                }else {
//                                    person.setGender(jRadioBtnMale.getText());
//                                }
//                                JOptionPane.showMessageDialog(this, "Person added!!", "Update",JOptionPane.INFORMATION_MESSAGE);
//                                clearFields();
//                            }
//                        }
//                    }
//                }
//            }
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(this, "Please enter all values","Error", JOptionPane.ERROR_MESSAGE);
//        }      
        if (checkBlankInput()==Boolean.TRUE)
        {
            Person person=personDirectory.addPerson();
            
            person.setPersonName(txtPersonName.getText());
            person.setAge(Integer.parseInt(txtAge.getText()));
            person.setHouse(txtHouse.getText());
            person.setCommunity(txtCommunity.getText());
            person.setCity(txtCity.getText());
            person.setZipcode(Integer.parseInt(txtZipCode1.getText()));
            
            
            if(jRadioBtnFemale.isSelected()){
                person.setGender(jRadioBtnFemale.getText());
            }else {
                person.setGender(jRadioBtnMale.getText());
            }
            
            JOptionPane.showMessageDialog(this, "Person added!!", "Update",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void txtPersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonNameActionPerformed

    private void jRadioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBtnMaleActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void jRadioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBtnFemaleActionPerformed

    private void txtZipCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCode1ActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnback1;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioBtnFemale;
    private javax.swing.JRadioButton jRadioBtnMale;
    private javax.swing.JLabel lblCityError;
    private javax.swing.JLabel lblCommunityError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPersonAgeError;
    private javax.swing.JLabel lblZipcodeError;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtZipCode1;
    // End of variables declaration//GEN-END:variables
}
